backend:
  name: git-gateway
  branch: main # O master, dependiendo del nombre de tu rama principal en GitHub

media_folder: "images" # Dónde se subirán las nuevas imágenes
public_folder: "/images" # Cómo se accederá a las imágenes desde la web

collections:
  - name: "paginas" # Nombre de la colección en el panel
    label: "Páginas" # Etiqueta visible en el panel
    files:
      - file: "sobre-nosotros.html"
        label: "Página 'Sobre Nosotros'"
        name: "sobre_nosotros"
        fields:
          - {label: "Título Principal de la Página", name: "titulo", widget: "string"}
          - {label: "Cuerpo de la Historia", name: "cuerpo", widget: "markdown"}
          - {label: "Imagen de Perfil", name: "imagen", widget: "image"}