backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Contenido de Páginas"
    files:
      - file: "src/_data/homepage.json"
        label: "Página de Inicio"
        name: "homepage"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
          - {label: "Título de Introducción", name: "intro_titulo", widget: "string"}
          - {label: "Texto de Introducción", name: "intro_texto", widget: "text"}
      # Aquí añadiremos las otras páginas como 'sobre_nosotros.json', etc.

  - name: "configuracion"
    label: "Configuración Global"
    files:
      - file: "src/_data/sitio.json"
        label: "Datos de Contacto"
        name: "sitio"
        fields:
          - {label: "Email de Contacto", name: "email", widget: "string"}
          - {label: "Teléfono de Contacto", name: "telefono", widget: "string"}
          - {label: "Enlace Instagram", name: "instagram_url", widget: "string"}
          - {label: "Enlace YouTube", name: "youtube_url", widget: "string"}