backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas Principales"
    files:
      - file: "src/_data/homepage.json"
        label: "Página de Inicio"
        name: "homepage"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
      - file: "src/_data/eventos.json"
        label: "Página de Eventos"
        name: "eventos"
        fields:
          - {label: "Título Principal", name: "titulo_principal", widget: "string"}
          - {label: "Texto Introducción", name: "texto_filosofia", widget: "markdown"}
      - file: "src/_data/sobre_nosotros.json"
        label: "Página 'Sobre Nosotros'"
        name: "sobre_nosotros"
        fields:
          - {label: "Cuerpo de la Historia", name: "historia_cuerpo", widget: "markdown"}
          - name: "equipo"
            label: "Miembros del Equipo"
            widget: "list"
            fields:
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Cargo", name: "cargo", widget: "string"}
              - {label: "Foto", name: "foto", widget: "image"}

  - name: "portafolio"
    label: "Portafolio"
    folder: "src/portafolio" # La carpeta donde vivirán los archivos .md
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Imagen", name: "image", widget: "image"}
      - {label: "Categoría", name: "category", widget: "select", options: ["bodas", "quince", "eventos", "producto", "retrato"]}
  
  - name: "servicios_cotizador"
    label: "Servicios del Cotizador"
    folder: "src/servicios" # La carpeta para los servicios
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre del Servicio", name: "title", widget: "string"}
      - {label: "Sección (Ej: Bodas, Quince, etc.)", name: "seccion", widget: "string"}
      - {label: "Tipo (Paquete o Adicional)", name: "tipo", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "string"}
      - {label: "Precio (sólo números)", name: "precio", widget: "number"}
