# Backend para conectar con GitHub a través de Netlify
backend:
  name: git-gateway
  branch: main

# Ruta donde se subirán las imágenes desde el CMS
media_folder: "src/images/uploads"
public_folder: "/images/uploads"

# Colecciones de contenido editable
collections:
  - name: "paginas"
    label: "Páginas Principales"
    files:
      - file: "src/_data/homepage.json"
        label: "Página de Inicio"
        name: "homepage"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
          - {label: "Título Introducción", name: "intro_titulo", widget: "string"}
          - {label: "Texto Introducción", name: "intro_texto", widget: "text"}
      - file: "src/_data/sobre_nosotros.json"
        label: "Página 'Sobre Nosotros'"
        name: "sobre_nosotros"
        fields:
          - {label: "Título de la Historia", name: "historia_titulo", widget: "string"}
          - {label: "Cuerpo de la Historia", name: "historia_cuerpo", widget: "markdown"}
          - {label: "Foto de la Historia", name: "historia_foto", widget: "image"}
          - name: "equipo"
            label: "Miembros del Equipo"
            widget: "list"
            fields:
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Cargo", name: "cargo", widget: "string"}
              - {label: "Foto", name: "foto", widget: "image"}
              - {label: "Cita", name: "cita", widget: "string"}
