backend:
  name: git-gateway
  branch: main

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Páginas Principales"
    files:
      - file: "src/_data/homepage.json"
        label: "Página de Inicio"
        name: "homepage"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
          - {label: "Título de Introducción", name: "intro_titulo", widget: "string"}
          - {label: "Texto de Introducción", name: "intro_texto", widget: "text"}
      - file: "src/_data/eventos.json"
        label: "Página de Eventos"
        name: "eventos"
        fields:
          - {label: "Título Principal", name: "titulo_principal", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
          - {label: "Título Filosofía", name: "titulo_filosofia", widget: "string"}
          - {label: "Texto Filosofía", name: "texto_filosofia", widget: "text"}
          - {label: "Título CTA Final", name: "titulo_cta", widget: "string"}
          - {label: "Texto CTA Final", name: "texto_cta", widget: "text"}
      - file: "src/_data/empresas.json"
        label: "Página de Empresas"
        name: "empresas"
        fields:
          - {label: "Título Principal", name: "titulo_principal", widget: "string"}
          - {label: "Subtítulo", name: "subtitulo", widget: "string"}
          - {label: "Título Intro", name: "titulo_intro", widget: "string"}
          - {label: "Texto Intro", name: "texto_intro", widget: "text"}
          - {label: "Lista de Beneficios", name: "beneficios", widget: "list"}
          - {label: "Título Proceso", name: "titulo_proceso", widget: "string"}
          - {label: "Texto Proceso", name: "texto_proceso", widget: "text"}
      - file: "src/_data/sobre_nosotros.json"
        label: "Página 'Sobre Nosotros'"
        name: "sobre_nosotros"
        fields:
          - {label: "Título Principal", name: "titulo_principal", widget: "string"}
          - {label: "Título de la Historia", name: "historia_titulo", widget: "string"}
          - {label: "Cuerpo de la Historia", name: "historia_cuerpo", widget: "markdown"}
          - {label: "Foto de la Historia (grande)", name: "historia_foto", widget: "image"}
          - name: "equipo"
            label: "Miembros del Equipo"
            widget: "list"
            fields:
              - {label: "Nombre", name: "nombre", widget: "string"}
              - {label: "Cargo", name: "cargo", widget: "string"}
              - {label: "Cita", name: "cita", widget: "string"}
              - {label: "Foto (pequeña y redonda)", name: "foto", widget: "image"}
  
  # --- El resto de las colecciones (Portafolio, Cotizador, etc.) no cambian ---
